apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-management
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kkuchima/workshop-assets
    targetRevision: main
    path: k8s/manifests/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false