apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: config-management
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: config-management tools
  sourceRepos:
    - "*"
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc