apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: hc-argo
  namespace: argocd
spec:
  default:
    logConfig:
      enabled: true
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: argocd-server